//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Student_Register.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int StdId { get; set; }
        public string StdName { get; set; }
        public string StdSurname { get; set; }
        public string StdMail { get; set; }
        public string StdPhoto { get; set; }
        public string StdAddress { get; set; }
    }
}
